### ISSUE TITLE
How to control the packet sending rate ?

### ISSUE THREAD

**Issue by meixsh** [EmreOvunc/Python-SYN-Flood-Attack-Tool#3]
@EmreOvunc Hello, I am using your script to imitate syn flooding attack, but I can not control the packet sending rate. Because the default rate is very low and it cannot up to my expectation.

**Comment by meixsh** [comment]
And another question is scapy will change my dstMac to be a broadcast address when I set the Ethernet dstMac to  be a fake address. I am not test it in a traditional network but in software defined network. So in fact the dstMac do not need to be in local machine arp cache. Could you help me to solve the question to make it just send what I set.

**Comment by EmreOvunc** [comment]
> @EmreOvunc Hello, I am using your script to imitate syn flooding attack, but I can not control the packet sending rate. Because the default rate is very low and it cannot up to my expectation.

Hi,

You can speed up the sending rate:

>      def run(self):
>          packets = "your packet list"
>          pkt_list = []
>          for pkt in packets:
>              # Build and send packet
>              pkt_list.append(pkt)
>          sendp(pkt_list, iface = eth0, verbose=0)

**Comment by EmreOvunc** [comment]
> @EmreOvunc And another question is `scapy` will change my `dstMac` to be a broadcast address when I set the Ethernet `dstMac` to be a fake address. I am not test it in a traditional network but in software defined network. So in fact the `dstMac` do not need to be in local machine arp cache. Could you help me to solve the question to make it just send what I set.

Which packet type did you use to change "dstMac"? SynFlood tool is using only 2 packet types, are ICMP and TCP.

**Comment by meixsh** [comment]
@EmreOvunc Yes, this method maybe could speed up the sending rate, but it still could not control the sending rate. For example, I want the script to send forged packets at a speed no less than 200 pkt/s, it still does not work. And most time we truly should control the sending rate. Changing dstMac because I need to miss flow table entry which is a concept in SDN environment.

**Comment by meixsh** [comment]
@EmreOvunc Do you know other methods in linux could control packet sending rate. I just found another tool called `ostinato` which also is a pretty good packet forge tool. Contrast to `scapy ` it could not program.

**Comment by EmreOvunc** [comment]
> @EmreOvunc Do you know other methods in linux could control packet sending rate. I just found another tool called `ostinato` which also is a pretty good packet forge tool. Contrast to `scapy ` it could not program.

If there is a limited rate of answers, you can specify a time interval to wait between two packets with the inter parameter. If some packets are lost or if specifying an interval is not enough, you can resend all the unanswered packets, either by calling the function again, directly with the unanswered list, or by specifying a retry parameter. If retry is 3, Scapy will try to resend unanswered packets 3 times. If retry is -3, Scapy will resend unanswered packets until no more answer is given for the same set of unanswered packets 3 times in a row. The timeout parameter specify the time to wait after the last packet has been sent:

> ### send(pck_list, inter=0.5,retry=-2,timeout=1)
> Begin emission:
> Finished to send 12 packets.
> Begin emission:
> Finished to send 9 packets.
> Begin emission:
> Finished to send 9 packets.
> 
> Received 100 packets, got 3 answers, remaining 9 packets
> (<Results: UDP:0 TCP:3 ICMP:0 Other:0>, <Unanswered: UDP:0 TCP:9 ICMP:0 Other:0>)
