### ISSUE TITLE
how to set random ttl value?

### ISSUE THREAD

**Issue by Nesyan** [EmreOvunc/Python-SYN-Flood-Attack-Tool#4]
Hi,
I want to use random ttl value in syn packets. Is there any way?

**Comment by EmreOvunc** [comment]
Yes, you can use random TTL values.

Just add the following code after line 29;
`IP_Packet.ttl=random.randint(100,254)`

**Comment by Nesyan** [comment]
thank you for your replying,
but it doesn't change for me.
I run a user space application on the destination system, is it possible
because of this the ttl value doesn't change?

thanks in advance

**Comment by EmreOvunc** [comment]
Could you send 2 packets to 10.10.10.10 IP address and also share tcpdump output.
`tcpdump src 10.10.10.10 and port 1234 -nn -vvv`

**Comment by Nesyan** [comment]
why this ip address and port?
I did it but there is not any output in tcpdump

**Comment by EmreOvunc** [comment]
I just wanted to see the contents of the packet. If there is no output in tcpdump, you are not sending. You can also use new version of the tool, written in python3.

**Comment by Nesyan** [comment]
no it is sending, I can see packets in destination machine but ttl value has default value.

**Comment by EmreOvunc** [comment]
When you set a static TTL value as follows, can you see it (for example ttl=123) from the tcpdump or wireshark?

```    	IP_Packet = IP ()
		IP_Packet.src = randomIP()
		IP_Packet.dst = dstIP
		IP_Packet.ttl = 123

		TCP_Packet = TCP ()
		TCP_Packet.sport = s_port
		TCP_Packet.dport = dstPort
		TCP_Packet.flags = "S"
		TCP_Packet.seq = s_eq
		TCP_Packet.window = w_indow
```

**Comment by Nesyan** [comment]
yes I can see it in source machine but in destination , I have an application with user space protocol stack and I am working with that, ttl doesnt change there!

**Comment by EmreOvunc** [comment]
You can try hping3 to validate time-to-live.
`hping3 --ttl 44 -S -c 1 IP`

If you can see the different ttl value from the destination host, you can continue with it.

**Comment by Nesyan** [comment]
I attached the output of hping3 and tcpdump on the source machine
and in the destination(10.10.10.1), ttl has default value(64)

**Comment by Nesyan** [comment]
tcpdump in the destiantion without running userspace protocol stack:
![tcpdump_dest](https://user-images.githubusercontent.com/38998748/64917525-c3bd0b00-d7a6-11e9-8300-a9100d940038.PNG)

**Comment by Nesyan** [comment]
these are tcpdump and hping outputs on source and with runing userspace protocol stack:
![hping3](https://user-images.githubusercontent.com/38998748/64918098-cd4a7100-d7ae-11e9-9cda-b260fe84d3c5.PNG)

![tcpdump](https://user-images.githubusercontent.com/38998748/64918082-8c525c80-d7ae-11e9-9604-7c4a215fa528.PNG)
I cant understand what is the problem!?

**Comment by EmreOvunc** [comment]
> tcpdump in the destiantion without running userspace protocol stack:
> ![tcpdump_dest](https://user-images.githubusercontent.com/38998748/64917525-c3bd0b00-d7a6-11e9-8300-a9100d940038.PNG)

In this picture, time-to-live values of the packets that you sent from 10.10.10.2 are 125. Packets with a TTL value of 64 are ICMP packets.
![resim](https://user-images.githubusercontent.com/15659223/64918254-5d36ed80-d7a4-11e9-92e0-bc4c1106e251.png)

**Comment by EmreOvunc** [comment]
> these are tcpdump and hping outputs on source and with runing userspace protocol stack:
> ![hping3](https://user-images.githubusercontent.com/38998748/64918098-cd4a7100-d7ae-11e9-9cda-b260fe84d3c5.PNG)
> 
> ![tcpdump](https://user-images.githubusercontent.com/38998748/64918082-8c525c80-d7ae-11e9-9604-7c4a215fa528.PNG)
> I cant understand what is the problem!?

You are right, I think it is about hping3. I sent Syn packet and captured destination traffic. I saw that hping3 said ttl is 64 but tcpdump/wireshark said ttl changed.

<img width="687" alt="resim" src="https://user-images.githubusercontent.com/15659223/64918275-aedf7800-d7a4-11e9-9ad1-ab1e16ab8adf.png">
<img width="482" alt="resim" src="https://user-images.githubusercontent.com/15659223/64918276-b1da6880-d7a4-11e9-9e23-bd8ebce33819.png">

**Comment by Nesyan** [comment]
> > tcpdump in the destiantion without running userspace protocol stack:
> > ![tcpdump_dest](https://user-images.githubusercontent.com/38998748/64917525-c3bd0b00-d7a6-11e9-8300-a9100d940038.PNG)
> 
> In this picture, time-to-live values of the packets that you sent from 10.10.10.2 are 125. Packets with a TTL value of 64 are ICMP packets.
> ![resim](https://user-images.githubusercontent.com/15659223/64918254-5d36ed80-d7a4-11e9-92e0-bc4c1106e251.png)

thank you for your helping.
about this picture, what's the problem? 
created packets with changed ttl values arrives to destination?right?

**Comment by EmreOvunc** [comment]
Yes, you sent SYN packets with ttl 125.
